version: '2'

services:
  core:
    build:
      context: ./core
    depends_on:
      - db
    expose:
      - 5000
    image: "core"

  db:
    environment:
      POSTGRES_PASSWORD: password
    image: postgres:10
    ports:
      - 5432:5432

  proxy-server:
    build:
      context: ./proxy-server
    depends_on:
      - core
    image: "proxy-server"
    ports:
      - 80:80
