version: '2'

services:
  core:
    build:
      context: ./core
    depends_on:
      - db
    expose:
      - 5000
    image: "core"
#    volumes:
#     - ./core:/var/www/core

  frontend:
    build:
      context: ./frontend
    expose:
      - 80
    image: "frontend"
    volumes:
      - ./frontend:/var/www/html

  db:
    environment:
      POSTGRES_PASSWORD: password
    image: postgres:10
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data

  proxy-server:
    build:
      context: ./proxy-server
    depends_on:
      - core
      - frontend
    image: "proxy-server"
    ports:
      - 80:80
